version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket dschultz-lambda-deploy --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml